[project]
name = "unified-mcp"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "africastalking>=2.0.1",
  "agnost>=0.1.8",
  "blaxel[core,telemetry]==0.2.25",
  "boto3>=1.41.5",
  "mcp[cli]>=1.22.0",
  "python-dotenv>=1.2.1",
  "pytz>=2025.2",
  "shinzo>=1.0.2",
]
